const data =[
    {
      id:1,
      img:"do_epic_shit.png",
      title:"left",
      desc:"description",
      inst:"instagram.com",
      fac:"facebook.com",
      twt:"twitter.com" 
    },
    {
      id:2,
      img:"do_epic_shit.png",
      title:"centre",
      desc:"description",
      inst:"instagram.com",
      fac:"facebook.com",
      twt:"twitter.com" 
    },
    {
      id:3,
      img:"do_epic_shit.png",
      title:"right",
      desc:"description",
      inst:"instagram.com",
      fac:"facebook.com",
      twt:"twitter.com" 
    },
    {
      id:4,
      img:"do_epic_shit.png",
      title:"right",
      desc:"description",
      inst:"instagram.com",
      fac:"facebook.com",
      twt:"twitter.com" 
    },
    {
      id:5,
      img:"do_epic_shit.png",
      title:"right",
      desc:"description",
      inst:"instagram.com",
      fac:"facebook.com",
      twt:"twitter.com" 
    },
    {
      id:6,
      img:"do_epic_shit.png",
      title:"right",
      desc:"description",
      inst:"instagram.com",
      fac:"facebook.com",
      twt:"twitter.com" 
    }
  ]

  export default data;